### PR TITLE
Cleaned and forked for standard nodejs/iojs.

### PR DESCRIPTION
**Pull request by marcominetti**
Just a suggestion: deploying compiled binaries could not be safe... I've cleaned the build/postinstall and bumped nan to version 1.8.x to support v8 4.2 (iojs 2.0.x)...

### CODE REVIEW

**Comment by marcominetti** [comment]
I suppose it's indeed a feature, so I close the pr.

**Comment by marcominetti** [comment]
Hi @SkyLined, I reopen this PR because the current build.cmd based approach makes using your lib quite tricky if there are not precompiled binaries (iojs 2.1?)...

What about allowing a mixed precompiled and autocompile for missing binaries?

**Comment by SkyLined** [comment]
The reason for the complexity is compatibility with previous versions of node.js. I have not tested, but it appears your PR strips all this to add compatibility with io.js 2.0.x. It will therefore probably not work with older versions of node.js. Can you please check this?

**Comment by marcominetti** [comment]
Correctly installs and compile and works with:
nodejs
0.10.38
0.11.13
0.12.4

iojs
1.0.2
1.8.1
2.1.0

For nodejs 0.8.9 and 0.9.9 I don't have tools installed but should work. Do you want to support that old versions?

**Comment by marcominetti** [comment]
Any news? Maybe using node-pre-gyp could be another solution to make install faster.

**Comment by SkyLined** [comment]
Sorry, been busy with other stuff.

I need people to be able to install it using npm without having to compile from source. This requires precompiled binaries. And various versions of Node have distinct requirements for compiled addons. Therefore, I need it to have a bunch of them: one that works for every supported version.

Might I suggest you create a fork for people who want to compile things themselves? If so, let me know so I can put a link in the documentation here for others that want the same thing as you.

**Comment by marcominetti** [comment]
Ok, can I name it cwinperfcounter-next?

**Comment by SkyLined** [comment]
Sure, you can name it whatever you want :)

**Pull request closed without merging**
